#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'package-lock.json'; then
  echo "📦 package-lock.json ha cambiado, correremos npm install para actualizar tus dependencias."
  npm install
fi